apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookmarker-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: api.bookmarker
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookmarker-api-svc
                port:
                  number: 8080